// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_esp_now

#ifndef _SQUARELINE_PROJECT_ESP_NOW_UI_H
#define _SQUARELINE_PROJECT_ESP_NOW_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_648622457);    // assets/clouds-and-sun-64.png
LV_IMG_DECLARE(ui_img_126643563);    // assets/fan2-24.png
LV_IMG_DECLARE(ui_img_1818346117);    // assets/sunrise-24.png
LV_IMG_DECLARE(ui_img_946304282);    // assets/sunset-24.png
LV_IMG_DECLARE(ui_img_316858971);    // assets/teardrop-24.png
LV_IMG_DECLARE(ui_img_287596344);    // assets/moisturizing-24.png
LV_IMG_DECLARE(ui_img_1897707657);    // assets/windspeed-24.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
