// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_esp_now

#include "ui.h"

// COMPONENT RL1

lv_obj_t * ui_RL1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_RL1;
    cui_RL1 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_RL1, 71);
    lv_obj_set_height(cui_RL1, 40);
    lv_obj_set_x(cui_RL1, -1);
    lv_obj_set_y(cui_RL1, -25);
    lv_obj_set_align(cui_RL1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_RL1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_RL1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_RL1_NUM);
    children[UI_COMP_RL1_RL1] = cui_RL1;
    lv_obj_add_event_cb(cui_RL1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_RL1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_RL1_create_hook(cui_RL1);
    return cui_RL1;
}

