// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_esp_now

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_LabelNode3;
extern lv_obj_t * ui_LabelNode3State;
extern lv_obj_t * ui_LabelNode3MCU;
extern lv_obj_t * ui_LabelNode3Temp;
extern lv_obj_t * ui_LabelNode3Humid;
extern lv_obj_t * ui_LabelNode3Flow;
extern lv_obj_t * ui_ArcTempNode3;
extern lv_obj_t * ui_LabelTempNode3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_ArcMCU3;
extern lv_obj_t * ui_LabelMCU3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ArcPWM;
extern lv_obj_t * ui_LabelPWM;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_LabelBT1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_LabelBT2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_LabelBT3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_LabelBT4;
extern lv_obj_t * ui_LabelTimeScreen2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

