// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_esp_now

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_LabelNode3 = NULL;
lv_obj_t * ui_LabelNode3State = NULL;
lv_obj_t * ui_LabelNode3MCU = NULL;
lv_obj_t * ui_LabelNode3Temp = NULL;
lv_obj_t * ui_LabelNode3Humid = NULL;
lv_obj_t * ui_LabelNode3Flow = NULL;
lv_obj_t * ui_ArcTempNode3 = NULL;
lv_obj_t * ui_LabelTempNode3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_ArcMCU3 = NULL;
lv_obj_t * ui_LabelMCU3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ArcPWM = NULL;
lv_obj_t * ui_LabelPWM = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_LabelBT1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_LabelBT2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_LabelBT3 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_LabelBT4 = NULL;
lv_obj_t * ui_LabelTimeScreen2 = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_RIGHT, 100, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_OVER_LEFT, 100, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 240);
    lv_obj_set_height(ui_Container2, 320);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel2, 150);
    lv_obj_set_height(ui_Panel2, 150);
    lv_obj_set_x(ui_Panel2, -40);
    lv_obj_set_y(ui_Panel2, -70);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xF77BE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelNode3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode3, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelNode3, "NODE MOTIVE");
    lv_obj_set_style_text_color(ui_LabelNode3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode3State = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelNode3State, 100);
    lv_obj_set_height(ui_LabelNode3State, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode3State, 0);
    lv_obj_set_y(ui_LabelNode3State, 20);
    lv_label_set_text(ui_LabelNode3State, "Connected");
    lv_obj_set_style_text_color(ui_LabelNode3State, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode3State, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelNode3State, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelNode3State, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelNode3State, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelNode3State, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode3MCU = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelNode3MCU, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LabelNode3MCU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode3MCU, 2);
    lv_obj_set_y(ui_LabelNode3MCU, 40);
    lv_label_set_text(ui_LabelNode3MCU, "MCU: 0°C");
    lv_obj_set_style_text_color(ui_LabelNode3MCU, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode3MCU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode3Temp = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelNode3Temp, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LabelNode3Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode3Temp, 2);
    lv_obj_set_y(ui_LabelNode3Temp, 60);
    lv_label_set_text(ui_LabelNode3Temp, "Temp:0°C");
    lv_obj_set_style_text_color(ui_LabelNode3Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode3Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode3Humid = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelNode3Humid, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LabelNode3Humid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode3Humid, 2);
    lv_obj_set_y(ui_LabelNode3Humid, 80);
    lv_label_set_text(ui_LabelNode3Humid, "Humi: 0 %");
    lv_obj_set_style_text_color(ui_LabelNode3Humid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode3Humid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode3Flow = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelNode3Flow, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LabelNode3Flow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode3Flow, 2);
    lv_obj_set_y(ui_LabelNode3Flow, 100);
    lv_label_set_text(ui_LabelNode3Flow, "Flow: 0%");
    lv_obj_set_style_text_color(ui_LabelNode3Flow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode3Flow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTempNode3 = lv_arc_create(ui_Container2);
    lv_obj_set_width(ui_ArcTempNode3, lv_pct(30));
    lv_obj_set_height(ui_ArcTempNode3, lv_pct(30));
    lv_obj_set_x(ui_ArcTempNode3, lv_pct(3));
    lv_obj_set_y(ui_ArcTempNode3, lv_pct(30));
    lv_obj_set_align(ui_ArcTempNode3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ArcTempNode3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_ArcTempNode3, 0);

    lv_obj_set_style_pad_left(ui_ArcTempNode3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcTempNode3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcTempNode3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcTempNode3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelTempNode3 = lv_label_create(ui_ArcTempNode3);
    lv_obj_set_width(ui_LabelTempNode3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempNode3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempNode3, 0);
    lv_obj_set_y(ui_LabelTempNode3, -10);
    lv_obj_set_align(ui_LabelTempNode3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempNode3, "0°C");
    lv_obj_set_style_text_align(ui_LabelTempNode3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempNode3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ArcTempNode3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 30);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "TEMP");

    ui_ArcMCU3 = lv_arc_create(ui_Container2);
    lv_obj_set_width(ui_ArcMCU3, lv_pct(30));
    lv_obj_set_height(ui_ArcMCU3, lv_pct(30));
    lv_obj_set_x(ui_ArcMCU3, lv_pct(35));
    lv_obj_set_y(ui_ArcMCU3, lv_pct(30));
    lv_obj_set_align(ui_ArcMCU3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ArcMCU3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_ArcMCU3, 0);

    lv_obj_set_style_pad_left(ui_ArcMCU3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcMCU3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcMCU3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcMCU3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelMCU3 = lv_label_create(ui_ArcMCU3);
    lv_obj_set_width(ui_LabelMCU3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMCU3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMCU3, 0);
    lv_obj_set_y(ui_LabelMCU3, -10);
    lv_obj_set_align(ui_LabelMCU3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMCU3, "0°C");
    lv_obj_set_style_text_align(ui_LabelMCU3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMCU3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ArcMCU3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 30);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "MCU3");

    ui_ArcPWM = lv_arc_create(ui_Container2);
    lv_obj_set_width(ui_ArcPWM, lv_pct(30));
    lv_obj_set_height(ui_ArcPWM, lv_pct(30));
    lv_obj_set_x(ui_ArcPWM, lv_pct(68));
    lv_obj_set_y(ui_ArcPWM, lv_pct(30));
    lv_obj_set_align(ui_ArcPWM, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ArcPWM, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_arc_set_value(ui_ArcPWM, 0);

    lv_obj_set_style_pad_left(ui_ArcPWM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcPWM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcPWM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcPWM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelPWM = lv_label_create(ui_ArcPWM);
    lv_obj_set_width(ui_LabelPWM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPWM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPWM, 0);
    lv_obj_set_y(ui_LabelPWM, -10);
    lv_obj_set_align(ui_LabelPWM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPWM, "0%");
    lv_obj_set_style_text_align(ui_LabelPWM, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPWM, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ArcPWM);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 30);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "PWM");

    ui_Panel3 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel3, 70);
    lv_obj_set_height(ui_Panel3, 150);
    lv_obj_set_x(ui_Panel3, 77);
    lv_obj_set_y(ui_Panel3, -70);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x6DCDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button1, lv_pct(142));
    lv_obj_set_height(ui_Button1, lv_pct(25));
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, -55);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBT1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_LabelBT1, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_LabelBT1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_LabelBT1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBT1, "Fan");

    ui_Button2 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button2, lv_pct(142));
    lv_obj_set_height(ui_Button2, lv_pct(25));
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, -20);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBT2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_LabelBT2, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_LabelBT2, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_LabelBT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBT2, "Light");

    ui_Button3 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button3, lv_pct(142));
    lv_obj_set_height(ui_Button3, lv_pct(25));
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, 20);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBT3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_LabelBT3, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_LabelBT3, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_LabelBT3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBT3, "Pump");

    ui_Button4 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button4, lv_pct(142));
    lv_obj_set_height(ui_Button4, lv_pct(25));
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 55);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBT4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_LabelBT4, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_LabelBT4, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_LabelBT4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBT4, "Opt");

    ui_LabelTimeScreen2 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LabelTimeScreen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimeScreen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimeScreen2, 0);
    lv_obj_set_y(ui_LabelTimeScreen2, 25);
    lv_obj_set_align(ui_LabelTimeScreen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimeScreen2, "00:00:00");
    lv_obj_set_style_text_font(ui_LabelTimeScreen2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Container2 = NULL;
    ui_Panel2 = NULL;
    ui_LabelNode3 = NULL;
    ui_LabelNode3State = NULL;
    ui_LabelNode3MCU = NULL;
    ui_LabelNode3Temp = NULL;
    ui_LabelNode3Humid = NULL;
    ui_LabelNode3Flow = NULL;
    ui_ArcTempNode3 = NULL;
    ui_LabelTempNode3 = NULL;
    ui_Label3 = NULL;
    ui_ArcMCU3 = NULL;
    ui_LabelMCU3 = NULL;
    ui_Label1 = NULL;
    ui_ArcPWM = NULL;
    ui_LabelPWM = NULL;
    ui_Label2 = NULL;
    ui_Panel3 = NULL;
    ui_Button1 = NULL;
    ui_LabelBT1 = NULL;
    ui_Button2 = NULL;
    ui_LabelBT2 = NULL;
    ui_Button3 = NULL;
    ui_LabelBT3 = NULL;
    ui_Button4 = NULL;
    ui_LabelBT4 = NULL;
    ui_LabelTimeScreen2 = NULL;

}
