// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_esp_now

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_LabelNode1;
extern lv_obj_t * ui_LabelNode1State;
extern lv_obj_t * ui_LabelNode1MCU;
extern lv_obj_t * ui_LabelNode1Temp;
extern lv_obj_t * ui_LabelNode1Humid;
extern lv_obj_t * ui_LabelNode1Light;
extern lv_obj_t * ui_LabelNode1Soil;
extern lv_obj_t * ui_ArcTemp;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_ArcHumid;
extern lv_obj_t * ui_LabelHumid;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_ArcMCU1;
extern lv_obj_t * ui_LabelMCU1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_LabelTimeScreen1;
extern lv_obj_t * ui_ArcMCU2;
extern lv_obj_t * ui_LabelMCU2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

