// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_esp_now

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_LabelWeather = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_LabelDate = NULL;
lv_obj_t * ui_LabelLocation = NULL;
lv_obj_t * ui_LabelLocalTempHumid = NULL;
lv_obj_t * ui_ImageWeatherState = NULL;
lv_obj_t * ui_LabelWeatherState = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_ImageAirQuality = NULL;
lv_obj_t * ui_ImageSunrise = NULL;
lv_obj_t * ui_ImageSunset = NULL;
lv_obj_t * ui_ImageRain = NULL;
lv_obj_t * ui_ImageMoisture = NULL;
lv_obj_t * ui_ImageWindspeed = NULL;
lv_obj_t * ui_LabelAirQuality = NULL;
lv_obj_t * ui_LabelSunrise = NULL;
lv_obj_t * ui_LabelSunset = NULL;
lv_obj_t * ui_LabelRain = NULL;
lv_obj_t * ui_LabelMoisture = NULL;
lv_obj_t * ui_LabelWindspeed = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_OVER_RIGHT, 100, 0, &ui_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_LEFT, 100, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_height(ui_Container3, lv_pct(100));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWeather = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_LabelWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeather, -30);
    lv_obj_set_y(ui_LabelWeather, -145);
    lv_obj_set_align(ui_LabelWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeather, "Today weather");
    lv_obj_set_style_text_font(ui_LabelWeather, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel4, lv_pct(90));
    lv_obj_set_height(ui_Panel4, lv_pct(40));
    lv_obj_set_x(ui_Panel4, lv_pct(0));
    lv_obj_set_y(ui_Panel4, lv_pct(10));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDate = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, 0);
    lv_obj_set_y(ui_LabelDate, 10);
    lv_label_set_text(ui_LabelDate, "Dec 21, 2025");

    ui_LabelLocation = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabelLocation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocation, 0);
    lv_obj_set_y(ui_LabelLocation, -5);
    lv_label_set_text(ui_LabelLocation, "Ho Chi Minh City, VN");

    ui_LabelLocalTempHumid = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabelLocalTempHumid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocalTempHumid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocalTempHumid, -39);
    lv_obj_set_y(ui_LabelLocalTempHumid, 13);
    lv_obj_set_align(ui_LabelLocalTempHumid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocalTempHumid, "26°C\n50%");
    lv_obj_set_style_text_font(ui_LabelLocalTempHumid, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeatherState = lv_img_create(ui_Panel4);
    lv_img_set_src(ui_ImageWeatherState, &ui_img_648622457);
    lv_obj_set_width(ui_ImageWeatherState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWeatherState, 55);
    lv_obj_set_y(ui_ImageWeatherState, 5);
    lv_obj_set_align(ui_ImageWeatherState, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeatherState, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherState, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWeatherState = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabelWeatherState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherState, 54);
    lv_obj_set_y(ui_LabelWeatherState, 49);
    lv_obj_set_align(ui_LabelWeatherState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeatherState, "Cloudy");

    ui_Panel6 = lv_obj_create(ui_Container3);
    lv_obj_set_height(ui_Panel6, 150);
    lv_obj_set_width(ui_Panel6, lv_pct(90));
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 80);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageAirQuality = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_ImageAirQuality, &ui_img_126643563);
    lv_obj_set_width(ui_ImageAirQuality, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageAirQuality, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageAirQuality, 20);
    lv_obj_set_y(ui_ImageAirQuality, 5);
    lv_obj_add_flag(ui_ImageAirQuality, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAirQuality, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageAirQuality, 450);

    ui_ImageSunrise = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_ImageSunrise, &ui_img_1818346117);
    lv_obj_set_width(ui_ImageSunrise, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageSunrise, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageSunrise, 0);
    lv_obj_set_y(ui_ImageSunrise, 5);
    lv_obj_set_align(ui_ImageSunrise, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ImageSunrise, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSunrise, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageSunrise, 450);

    ui_ImageSunset = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_ImageSunset, &ui_img_946304282);
    lv_obj_set_width(ui_ImageSunset, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageSunset, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageSunset, -20);
    lv_obj_set_y(ui_ImageSunset, 5);
    lv_obj_set_align(ui_ImageSunset, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageSunset, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSunset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageSunset, 450);

    ui_ImageRain = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_ImageRain, &ui_img_316858971);
    lv_obj_set_width(ui_ImageRain, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageRain, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageRain, 20);
    lv_obj_set_y(ui_ImageRain, lv_pct(-20));
    lv_obj_set_align(ui_ImageRain, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ImageRain, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageRain, 450);

    ui_ImageMoisture = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_ImageMoisture, &ui_img_287596344);
    lv_obj_set_width(ui_ImageMoisture, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageMoisture, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageMoisture, 0);
    lv_obj_set_y(ui_ImageMoisture, -20);
    lv_obj_set_align(ui_ImageMoisture, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImageMoisture, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMoisture, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageMoisture, 450);

    ui_ImageWindspeed = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_ImageWindspeed, &ui_img_1897707657);
    lv_obj_set_width(ui_ImageWindspeed, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageWindspeed, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageWindspeed, -20);
    lv_obj_set_y(ui_ImageWindspeed, -20);
    lv_obj_set_align(ui_ImageWindspeed, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ImageWindspeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWindspeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageWindspeed, 450);

    ui_LabelAirQuality = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_LabelAirQuality, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAirQuality, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAirQuality, -63);
    lv_obj_set_y(ui_LabelAirQuality, lv_pct(36));
    lv_obj_set_align(ui_LabelAirQuality, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelAirQuality, "0%");
    lv_obj_set_style_text_align(ui_LabelAirQuality, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSunrise = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_LabelSunrise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSunrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSunrise, 0);
    lv_obj_set_y(ui_LabelSunrise, lv_pct(35));
    lv_obj_set_align(ui_LabelSunrise, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelSunrise, "00:00");

    ui_LabelSunset = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_LabelSunset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSunset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSunset, -10);
    lv_obj_set_y(ui_LabelSunset, lv_pct(35));
    lv_obj_set_align(ui_LabelSunset, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelSunset, "00:00");

    ui_LabelRain = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_LabelRain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRain, 20);
    lv_obj_set_y(ui_LabelRain, lv_pct(5));
    lv_obj_set_align(ui_LabelRain, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LabelRain, "0%");

    ui_LabelMoisture = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_LabelMoisture, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMoisture, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMoisture, 0);
    lv_obj_set_y(ui_LabelMoisture, lv_pct(5));
    lv_obj_set_align(ui_LabelMoisture, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelMoisture, "0%");

    ui_LabelWindspeed = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_LabelWindspeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWindspeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWindspeed, -10);
    lv_obj_set_y(ui_LabelWindspeed, lv_pct(5));
    lv_obj_set_align(ui_LabelWindspeed, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_LabelWindspeed, "0m/s");

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Container3 = NULL;
    ui_LabelWeather = NULL;
    ui_Panel4 = NULL;
    ui_LabelDate = NULL;
    ui_LabelLocation = NULL;
    ui_LabelLocalTempHumid = NULL;
    ui_ImageWeatherState = NULL;
    ui_LabelWeatherState = NULL;
    ui_Panel6 = NULL;
    ui_ImageAirQuality = NULL;
    ui_ImageSunrise = NULL;
    ui_ImageSunset = NULL;
    ui_ImageRain = NULL;
    ui_ImageMoisture = NULL;
    ui_ImageWindspeed = NULL;
    ui_LabelAirQuality = NULL;
    ui_LabelSunrise = NULL;
    ui_LabelSunset = NULL;
    ui_LabelRain = NULL;
    ui_LabelMoisture = NULL;
    ui_LabelWindspeed = NULL;

}
