// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_esp_now

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_LabelWeather;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelLocation;
extern lv_obj_t * ui_LabelLocalTempHumid;
extern lv_obj_t * ui_ImageWeatherState;
extern lv_obj_t * ui_LabelWeatherState;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_ImageAirQuality;
extern lv_obj_t * ui_ImageSunrise;
extern lv_obj_t * ui_ImageSunset;
extern lv_obj_t * ui_ImageRain;
extern lv_obj_t * ui_ImageMoisture;
extern lv_obj_t * ui_ImageWindspeed;
extern lv_obj_t * ui_LabelAirQuality;
extern lv_obj_t * ui_LabelSunrise;
extern lv_obj_t * ui_LabelSunset;
extern lv_obj_t * ui_LabelRain;
extern lv_obj_t * ui_LabelMoisture;
extern lv_obj_t * ui_LabelWindspeed;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

