// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_esp_now

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_LabelNode1 = NULL;
lv_obj_t * ui_LabelNode1State = NULL;
lv_obj_t * ui_LabelNode1MCU = NULL;
lv_obj_t * ui_LabelNode1Temp = NULL;
lv_obj_t * ui_LabelNode1Humid = NULL;
lv_obj_t * ui_LabelNode1Light = NULL;
lv_obj_t * ui_LabelNode1Soil = NULL;
lv_obj_t * ui_ArcTemp = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_ArcHumid = NULL;
lv_obj_t * ui_LabelHumid = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_ArcMCU1 = NULL;
lv_obj_t * ui_LabelMCU1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_LabelTimeScreen1 = NULL;
lv_obj_t * ui_ArcMCU2 = NULL;
lv_obj_t * ui_LabelMCU2 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_OVER_LEFT, 100, 0, &ui_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_OVER_RIGHT, 100, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 240);
    lv_obj_set_height(ui_Container1, 320);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel1, 150);
    lv_obj_set_height(ui_Panel1, 159);
    lv_obj_set_x(ui_Panel1, -40);
    lv_obj_set_y(ui_Panel1, -70);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x58AA59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelNode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelNode1, "NODE SENSE");
    lv_obj_set_style_text_color(ui_LabelNode1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode1State = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelNode1State, 100);
    lv_obj_set_height(ui_LabelNode1State, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode1State, 0);
    lv_obj_set_y(ui_LabelNode1State, 20);
    lv_label_set_text(ui_LabelNode1State, "Connected");
    lv_obj_set_style_text_color(ui_LabelNode1State, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode1State, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelNode1State, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelNode1State, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelNode1State, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelNode1State, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode1MCU = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelNode1MCU, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LabelNode1MCU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode1MCU, 2);
    lv_obj_set_y(ui_LabelNode1MCU, 40);
    lv_label_set_text(ui_LabelNode1MCU, "MCU: 0°C");
    lv_obj_set_style_text_color(ui_LabelNode1MCU, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode1MCU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode1Temp = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelNode1Temp, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LabelNode1Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode1Temp, 2);
    lv_obj_set_y(ui_LabelNode1Temp, 60);
    lv_label_set_text(ui_LabelNode1Temp, "Temperature:0°C");
    lv_obj_set_style_text_color(ui_LabelNode1Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode1Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode1Humid = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelNode1Humid, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LabelNode1Humid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode1Humid, 2);
    lv_obj_set_y(ui_LabelNode1Humid, 80);
    lv_label_set_text(ui_LabelNode1Humid, "Humidity: 0%");
    lv_obj_set_style_text_color(ui_LabelNode1Humid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode1Humid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode1Light = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelNode1Light, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LabelNode1Light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode1Light, 2);
    lv_obj_set_y(ui_LabelNode1Light, 100);
    lv_label_set_text(ui_LabelNode1Light, "Light: 0%");
    lv_obj_set_style_text_color(ui_LabelNode1Light, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode1Light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode1Soil = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelNode1Soil, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LabelNode1Soil, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode1Soil, 2);
    lv_obj_set_y(ui_LabelNode1Soil, 120);
    lv_label_set_text(ui_LabelNode1Soil, "Soil moisture: 0%");
    lv_obj_set_style_text_color(ui_LabelNode1Soil, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNode1Soil, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemp = lv_arc_create(ui_Container1);
    lv_obj_set_width(ui_ArcTemp, lv_pct(30));
    lv_obj_set_height(ui_ArcTemp, lv_pct(30));
    lv_obj_set_x(ui_ArcTemp, lv_pct(3));
    lv_obj_set_y(ui_ArcTemp, lv_pct(30));
    lv_obj_set_align(ui_ArcTemp, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ArcTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_ArcTemp, 0);

    lv_obj_set_style_pad_left(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_ArcTemp);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, 0);
    lv_obj_set_y(ui_LabelTemp, -10);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "0°C");
    lv_obj_set_style_text_align(ui_LabelTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ArcTemp);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "TEMP");

    ui_ArcHumid = lv_arc_create(ui_Container1);
    lv_obj_set_width(ui_ArcHumid, lv_pct(30));
    lv_obj_set_height(ui_ArcHumid, lv_pct(30));
    lv_obj_set_x(ui_ArcHumid, lv_pct(35));
    lv_obj_set_y(ui_ArcHumid, lv_pct(30));
    lv_obj_set_align(ui_ArcHumid, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ArcHumid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_ArcHumid, 0);

    lv_obj_set_style_pad_left(ui_ArcHumid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcHumid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcHumid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcHumid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelHumid = lv_label_create(ui_ArcHumid);
    lv_obj_set_width(ui_LabelHumid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumid, 0);
    lv_obj_set_y(ui_LabelHumid, -10);
    lv_obj_set_align(ui_LabelHumid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumid, "0%");
    lv_obj_set_style_text_align(ui_LabelHumid, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumid, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_ArcHumid);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 30);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "HUMID");

    ui_ArcMCU1 = lv_arc_create(ui_Container1);
    lv_obj_set_width(ui_ArcMCU1, lv_pct(30));
    lv_obj_set_height(ui_ArcMCU1, lv_pct(30));
    lv_obj_set_x(ui_ArcMCU1, lv_pct(68));
    lv_obj_set_y(ui_ArcMCU1, lv_pct(30));
    lv_obj_set_align(ui_ArcMCU1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ArcMCU1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_arc_set_value(ui_ArcMCU1, 0);

    lv_obj_set_style_pad_left(ui_ArcMCU1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcMCU1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcMCU1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcMCU1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelMCU1 = lv_label_create(ui_ArcMCU1);
    lv_obj_set_width(ui_LabelMCU1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMCU1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMCU1, 0);
    lv_obj_set_y(ui_LabelMCU1, -10);
    lv_obj_set_align(ui_LabelMCU1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMCU1, "0°C");
    lv_obj_set_style_text_align(ui_LabelMCU1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMCU1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_ArcMCU1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 30);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "MCU1");

    ui_LabelTimeScreen1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelTimeScreen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimeScreen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimeScreen1, 0);
    lv_obj_set_y(ui_LabelTimeScreen1, 25);
    lv_obj_set_align(ui_LabelTimeScreen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimeScreen1, "00:00:00");
    lv_obj_set_style_text_font(ui_LabelTimeScreen1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcMCU2 = lv_arc_create(ui_Container1);
    lv_obj_set_width(ui_ArcMCU2, lv_pct(30));
    lv_obj_set_height(ui_ArcMCU2, lv_pct(30));
    lv_obj_set_x(ui_ArcMCU2, lv_pct(68));
    lv_obj_set_y(ui_ArcMCU2, lv_pct(-8));
    lv_obj_set_align(ui_ArcMCU2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ArcMCU2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_arc_set_value(ui_ArcMCU2, 60);
    lv_obj_set_style_arc_rounded(ui_ArcMCU2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_rounded(ui_ArcMCU2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcMCU2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcMCU2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcMCU2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcMCU2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcMCU2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcMCU2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelMCU2 = lv_label_create(ui_ArcMCU2);
    lv_obj_set_width(ui_LabelMCU2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMCU2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMCU2, 0);
    lv_obj_set_y(ui_LabelMCU2, -10);
    lv_obj_set_align(ui_LabelMCU2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMCU2, "0°C");
    lv_obj_set_style_text_align(ui_LabelMCU2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMCU2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_ArcMCU2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 15);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "MCU2");

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 70);
    lv_obj_set_height(ui_Panel5, 70);
    lv_obj_set_x(ui_Panel5, 77);
    lv_obj_set_y(ui_Panel5, -114);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x6DCDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "IP: 192.\n168.x.xx");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container1 = NULL;
    ui_Panel1 = NULL;
    ui_LabelNode1 = NULL;
    ui_LabelNode1State = NULL;
    ui_LabelNode1MCU = NULL;
    ui_LabelNode1Temp = NULL;
    ui_LabelNode1Humid = NULL;
    ui_LabelNode1Light = NULL;
    ui_LabelNode1Soil = NULL;
    ui_ArcTemp = NULL;
    ui_LabelTemp = NULL;
    ui_Label4 = NULL;
    ui_ArcHumid = NULL;
    ui_LabelHumid = NULL;
    ui_Label5 = NULL;
    ui_ArcMCU1 = NULL;
    ui_LabelMCU1 = NULL;
    ui_Label6 = NULL;
    ui_LabelTimeScreen1 = NULL;
    ui_ArcMCU2 = NULL;
    ui_LabelMCU2 = NULL;
    ui_Label8 = NULL;
    ui_Panel5 = NULL;
    ui_Label7 = NULL;

}
