; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	olikraus/U8g2@^2.36.15
	br3ttb/PID @ ^1.2.1
	paulstoffregen/Encoder@^1.4.4
	links2004/WebSockets@^2.7.1
monitor_speed = 115200
monitor_port = COM4
upload_protocol = espota
upload_port = 192.168.2.45
