SET(SOURCES ui_comp_rl1.c
    ui_comp.c
    ui_Screen0.c
    ui_Screen1.c
    ui_Screen2.c
    ui_Screen3.c
    ui_Screen4.c
    ui_Screen6.c
    ui_Screen7.c
    ui_Screen8.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_events.c
    ui_img_611426437.c
    ui_img_290163073.c
    ui_img_25085410.c
    ui_img_1286666203.c
    ui_img_471554236.c
    ui_img_316858971.c
    ui_img_1085318842.c
    ui_img_513413048.c
    ui_img_923752334.c
    ui_img_947216078.c
    ui_img_749987781.c
    ui_img_1564025377.c
    ui_img_1351346451.c
    ui_img_497137438.c
    ui_img_1277404635.c
    ui_img_1300861977.c
    ui_img_1381526408.c
    ui_img_599427730.c
    ui_img_1704994528.c
    ui_img_1666319769.c
    fonts/ui_font_Font7segment14.c)

add_library(ui ${SOURCES})
