// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#ifndef _SQUARELINE_PROJECT_FARMING_UI_H
#define _SQUARELINE_PROJECT_FARMING_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen0.h"
#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen6.h"
#include "ui_Screen7.h"
#include "ui_Screen8.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_611426437);    // assets/bolt-24.png
LV_IMG_DECLARE(ui_img_290163073);    // assets/meter-24.png
LV_IMG_DECLARE(ui_img_25085410);    // assets/sun-24.png
LV_IMG_DECLARE(ui_img_1286666203);    // assets/fan-24.png
LV_IMG_DECLARE(ui_img_471554236);    // assets/cloudy-24.png
LV_IMG_DECLARE(ui_img_316858971);    // assets/teardrop-24.png
LV_IMG_DECLARE(ui_img_1085318842);    // assets/wind-24.png
LV_IMG_DECLARE(ui_img_513413048);    // assets/snowflake-24.png
LV_IMG_DECLARE(ui_img_923752334);    // assets/wifi-slash-16.png
LV_IMG_DECLARE(ui_img_947216078);    // assets/wifi-16.png
LV_IMG_DECLARE(ui_img_749987781);    // assets/link-16.png
LV_IMG_DECLARE(ui_img_1564025377);    // assets/link-slash-alt-16.png
LV_IMG_DECLARE(ui_img_1351346451);    // assets/bell-notification-social-media-16.png
LV_IMG_DECLARE(ui_img_497137438);    // assets/bell-slash-16.png
LV_IMG_DECLARE(ui_img_1277404635);    // assets/wifi-slash-24.png
LV_IMG_DECLARE(ui_img_1300861977);    // assets/wifi-24.png
LV_IMG_DECLARE(ui_img_1381526408);    // assets/link-24.png
LV_IMG_DECLARE(ui_img_599427730);    // assets/link-slash-alt-24.png
LV_IMG_DECLARE(ui_img_1704994528);    // assets/bell-notification-social-media-24.png
LV_IMG_DECLARE(ui_img_1666319769);    // assets/bell-slash-24.png

// FONTS
LV_FONT_DECLARE(ui_font_Font7segment14);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
