// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#ifndef _UI_COMP_RL1_H
#define _UI_COMP_RL1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT RL1
#define UI_COMP_RL1_RL1 0
#define _UI_COMP_RL1_NUM 1
lv_obj_t * ui_RL1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
