// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Pump_Click_callback(lv_event_t * e);
void Light_Click_callback(lv_event_t * e);
void Mode_callback(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
