// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#include "ui.h"

void Pump_Click_callback(lv_event_t * e)
{
	// Your code here
}

void Light_Click_callback(lv_event_t * e)
{
	// Your code here
}

void Mode_callback(lv_event_t * e)
{
	// Your code here
}
