// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_PanelTimesetting;
extern lv_obj_t * ui_RollerMinute;
extern lv_obj_t * ui_RollerHour;
extern lv_obj_t * ui_PanelTimeButton;
extern void ui_event_ButtonSet(lv_event_t * e);
extern lv_obj_t * ui_ButtonSet;
extern lv_obj_t * ui_LabelBTNSet;
extern void ui_event_ButtonClear(lv_event_t * e);
extern lv_obj_t * ui_ButtonClear;
extern lv_obj_t * ui_LabelBTNClear;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Calendar1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

