// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_ContainerChart = NULL;
lv_obj_t * ui_PanelChartTemp = NULL;
lv_obj_t * ui_ChartTemp = NULL;
lv_obj_t * ui_PanelChartHumid = NULL;
lv_obj_t * ui_ChartHumid = NULL;
lv_obj_t * ui_PanelChartSoid = NULL;
lv_obj_t * ui_ChartSoid = NULL;
lv_obj_t * ui_LabelChartTemp = NULL;
lv_obj_t * ui_LabelChartHumid = NULL;
lv_obj_t * ui_LabelChartSoild = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_RIGHT, 100, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerChart = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_ContainerChart);
    lv_obj_set_width(ui_ContainerChart, lv_pct(100));
    lv_obj_set_height(ui_ContainerChart, lv_pct(100));
    lv_obj_set_align(ui_ContainerChart, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerChart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerChart, lv_color_hex(0xB3DBBA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerChart, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelChartTemp = lv_obj_create(ui_ContainerChart);
    lv_obj_set_width(ui_PanelChartTemp, lv_pct(90));
    lv_obj_set_height(ui_PanelChartTemp, lv_pct(30));
    lv_obj_set_x(ui_PanelChartTemp, 5);
    lv_obj_set_y(ui_PanelChartTemp, -100);
    lv_obj_set_align(ui_PanelChartTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelChartTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelChartTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelChartTemp, lv_color_hex(0x1EA457), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChartTemp, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelChartTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelChartTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTemp = lv_chart_create(ui_PanelChartTemp);
    lv_obj_set_width(ui_ChartTemp, lv_pct(105));
    lv_obj_set_height(ui_ChartTemp, lv_pct(104));
    lv_obj_set_align(ui_ChartTemp, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartTemp, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_ChartTemp, LV_CHART_AXIS_PRIMARY_Y, 0, 50);
    lv_chart_set_range(ui_ChartTemp, LV_CHART_AXIS_SECONDARY_Y, 0, 50);
    lv_chart_set_axis_tick(ui_ChartTemp, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartTemp, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartTemp, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_ChartTemp_series_1 = lv_chart_add_series(ui_ChartTemp, lv_color_hex(0x808080),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartTemp_series_1_array[] = { 29, 29, 30, 29, 28, 27, 28, 27, 29 };
    lv_chart_set_ext_y_array(ui_ChartTemp, ui_ChartTemp_series_1, ui_ChartTemp_series_1_array);
    lv_obj_set_style_radius(ui_ChartTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartTemp, lv_color_hex(0xF54A19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartTemp, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ChartTemp, lv_color_hex(0x8DFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChartTemp, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ChartTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ChartTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_ChartTemp, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_ChartTemp, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartTemp, lv_color_hex(0xD4F6DF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartTemp, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_PanelChartHumid = lv_obj_create(ui_ContainerChart);
    lv_obj_set_width(ui_PanelChartHumid, lv_pct(90));
    lv_obj_set_height(ui_PanelChartHumid, lv_pct(30));
    lv_obj_set_x(ui_PanelChartHumid, 5);
    lv_obj_set_y(ui_PanelChartHumid, 0);
    lv_obj_set_align(ui_PanelChartHumid, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelChartHumid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelChartHumid, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelChartHumid, lv_color_hex(0x1EA457), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChartHumid, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelChartHumid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelChartHumid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartHumid = lv_chart_create(ui_PanelChartHumid);
    lv_obj_set_width(ui_ChartHumid, lv_pct(105));
    lv_obj_set_height(ui_ChartHumid, lv_pct(104));
    lv_obj_set_align(ui_ChartHumid, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartHumid, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_ChartHumid, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartHumid, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartHumid, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_ChartHumid_series_1 = lv_chart_add_series(ui_ChartHumid, lv_color_hex(0x808080),
                                                                     LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartHumid_series_1_array[] = { 80, 70, 60, 40, 90, 85, 90, 90, 100, 75 };
    lv_chart_set_ext_y_array(ui_ChartHumid, ui_ChartHumid_series_1, ui_ChartHumid_series_1_array);
    lv_obj_set_style_radius(ui_ChartHumid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartHumid, lv_color_hex(0x95D4F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartHumid, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ChartHumid, lv_color_hex(0xFBA027), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChartHumid, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartHumid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartHumid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_ChartHumid, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_ChartHumid, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartHumid, lv_color_hex(0xD4F6DF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartHumid, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_PanelChartSoid = lv_obj_create(ui_ContainerChart);
    lv_obj_set_width(ui_PanelChartSoid, lv_pct(90));
    lv_obj_set_height(ui_PanelChartSoid, lv_pct(30));
    lv_obj_set_x(ui_PanelChartSoid, 5);
    lv_obj_set_y(ui_PanelChartSoid, 100);
    lv_obj_set_align(ui_PanelChartSoid, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelChartSoid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelChartSoid, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelChartSoid, lv_color_hex(0x1EA457), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChartSoid, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelChartSoid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelChartSoid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartSoid = lv_chart_create(ui_PanelChartSoid);
    lv_obj_set_width(ui_ChartSoid, lv_pct(105));
    lv_obj_set_height(ui_ChartSoid, lv_pct(104));
    lv_obj_set_align(ui_ChartSoid, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartSoid, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_ChartSoid, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartSoid, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartSoid, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_ChartSoid_series_1 = lv_chart_add_series(ui_ChartSoid, lv_color_hex(0x808080),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartSoid_series_1_array[] = { 60, 67, 45, 40, 43, 60, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_ChartSoid, ui_ChartSoid_series_1, ui_ChartSoid_series_1_array);
    lv_obj_set_style_radius(ui_ChartSoid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartSoid, lv_color_hex(0x95D4F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartSoid, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ChartSoid, lv_color_hex(0xFBA027), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChartSoid, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartSoid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartSoid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ChartSoid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ChartSoid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_ChartSoid, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_ChartSoid, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartSoid, lv_color_hex(0xD4F6DF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartSoid, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_LabelChartTemp = lv_label_create(ui_ContainerChart);
    lv_obj_set_width(ui_LabelChartTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChartTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChartTemp, -85);
    lv_obj_set_y(ui_LabelChartTemp, -113);
    lv_obj_set_align(ui_LabelChartTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChartTemp, "Temp");
    lv_obj_set_style_text_color(ui_LabelChartTemp, lv_color_hex(0xF3E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChartTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_LabelChartTemp, 900, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LabelChartTemp, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChartHumid = lv_label_create(ui_ContainerChart);
    lv_obj_set_width(ui_LabelChartHumid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChartHumid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChartHumid, -80);
    lv_obj_set_y(ui_LabelChartHumid, -15);
    lv_obj_set_align(ui_LabelChartHumid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChartHumid, "Humid");
    lv_obj_set_style_text_color(ui_LabelChartHumid, lv_color_hex(0xF3E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChartHumid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_LabelChartHumid, 900, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LabelChartHumid, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChartSoild = lv_label_create(ui_ContainerChart);
    lv_obj_set_width(ui_LabelChartSoild, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChartSoild, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChartSoild, -88);
    lv_obj_set_y(ui_LabelChartSoild, 95);
    lv_obj_set_align(ui_LabelChartSoild, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChartSoild, "Soid");
    lv_obj_set_style_text_color(ui_LabelChartSoild, lv_color_hex(0xF3E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChartSoild, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_LabelChartSoild, 900, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LabelChartSoild, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_ContainerChart = NULL;
    ui_PanelChartTemp = NULL;
    ui_ChartTemp = NULL;
    ui_PanelChartHumid = NULL;
    ui_ChartHumid = NULL;
    ui_PanelChartSoid = NULL;
    ui_ChartSoid = NULL;
    ui_LabelChartTemp = NULL;
    ui_LabelChartHumid = NULL;
    ui_LabelChartSoild = NULL;

}
