// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_Screen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea2);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 240);
    lv_obj_set_height(ui_Container7, 320);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container7, lv_color_hex(0xAFD5C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Container7);
    lv_obj_set_width(ui_TextArea1, lv_pct(90));
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, lv_pct(5));
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_TOP_MID);
    lv_textarea_set_max_length(ui_TextArea1, 512);
    lv_textarea_set_placeholder_text(ui_TextArea1, "WiFi");
    lv_textarea_set_one_line(ui_TextArea1, true);

    ui_TextArea2 = lv_textarea_create(ui_Container7);
    lv_obj_set_width(ui_TextArea2, lv_pct(90));
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_TextArea2, 0);
    lv_obj_set_y(ui_TextArea2, lv_pct(17));
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_TOP_MID);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Password");
    lv_textarea_set_one_line(ui_TextArea2, true);
    lv_textarea_set_password_mode(ui_TextArea2, true);

    ui_Keyboard1 = lv_keyboard_create(ui_Container7);
    lv_obj_set_height(ui_Keyboard1, 160);
    lv_obj_set_width(ui_Keyboard1, lv_pct(100));
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0xA4FCA6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Container7 = NULL;
    ui_TextArea1 = NULL;
    ui_TextArea2 = NULL;
    ui_Keyboard1 = NULL;

}
