// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#ifndef UI_SCREEN8_H
#define UI_SCREEN8_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen8
extern void ui_Screen8_screen_init(void);
extern void ui_Screen8_screen_destroy(void);
extern void ui_event_Screen8(lv_event_t * e);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_PanelValue1;
extern lv_obj_t * ui_Value1Max;
extern lv_obj_t * ui_Value1Min;
extern lv_obj_t * ui_LabelValue1;
extern lv_obj_t * ui_PanelValue2;
extern lv_obj_t * ui_Value2Max;
extern lv_obj_t * ui_Value2Min;
extern lv_obj_t * ui_LabelValue2;
extern lv_obj_t * ui_PanelValue3;
extern lv_obj_t * ui_Value3Max;
extern lv_obj_t * ui_Value3Min;
extern lv_obj_t * ui_LabelValue3;
extern lv_obj_t * ui_PanelValue4;
extern lv_obj_t * ui_Value4Max;
extern lv_obj_t * ui_Value4Min;
extern lv_obj_t * ui_LabelValue4;
extern lv_obj_t * ui_PanelValue5;
extern lv_obj_t * ui_Value5Max;
extern lv_obj_t * ui_Value5Min;
extern lv_obj_t * ui_LabelValue5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

