// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_ContainerChart;
extern lv_obj_t * ui_PanelChartTemp;
extern lv_obj_t * ui_ChartTemp;
extern lv_obj_t * ui_PanelChartHumid;
extern lv_obj_t * ui_ChartHumid;
extern lv_obj_t * ui_PanelChartSoid;
extern lv_obj_t * ui_ChartSoid;
extern lv_obj_t * ui_LabelChartTemp;
extern lv_obj_t * ui_LabelChartHumid;
extern lv_obj_t * ui_LabelChartSoild;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

