// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_ContainerSetting = NULL;
lv_obj_t * ui_PanelInternet = NULL;
lv_obj_t * ui_LabelPanelInternet = NULL;
lv_obj_t * ui_PanelTime = NULL;
lv_obj_t * ui_LabelPanelTime = NULL;
lv_obj_t * ui_PanelUpdate = NULL;
lv_obj_t * ui_LabelPanelUpdate = NULL;
lv_obj_t * ui_PanelValue = NULL;
lv_obj_t * ui_LabelPanelValue = NULL;
lv_obj_t * ui_PanelConnect = NULL;
lv_obj_t * ui_WiFiDisconnected = NULL;
lv_obj_t * ui_WiFiConnected = NULL;
lv_obj_t * ui_LoraConnected = NULL;
lv_obj_t * ui_LoraDisonnected = NULL;
lv_obj_t * ui_Bell = NULL;
lv_obj_t * ui_Bellflash = NULL;
lv_obj_t * ui_LabelTime = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_PanelInternet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_PanelTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_PanelUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen7_screen_init);
    }
}

void ui_event_PanelValue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen8_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerSetting = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_ContainerSetting);
    lv_obj_set_width(ui_ContainerSetting, 240);
    lv_obj_set_height(ui_ContainerSetting, 320);
    lv_obj_set_align(ui_ContainerSetting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerSetting, lv_color_hex(0x97F3C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSetting, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelInternet = lv_obj_create(ui_ContainerSetting);
    lv_obj_set_height(ui_PanelInternet, 50);
    lv_obj_set_width(ui_PanelInternet, lv_pct(90));
    lv_obj_set_x(ui_PanelInternet, 0);
    lv_obj_set_y(ui_PanelInternet, lv_pct(20));
    lv_obj_set_align(ui_PanelInternet, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelInternet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPanelInternet = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_LabelPanelInternet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelInternet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPanelInternet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelInternet, "INTERNET");

    ui_PanelTime = lv_obj_create(ui_ContainerSetting);
    lv_obj_set_height(ui_PanelTime, 50);
    lv_obj_set_width(ui_PanelTime, lv_pct(90));
    lv_obj_set_x(ui_PanelTime, 0);
    lv_obj_set_y(ui_PanelTime, lv_pct(40));
    lv_obj_set_align(ui_PanelTime, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPanelTime = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_LabelPanelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPanelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelTime, "TIME");

    ui_PanelUpdate = lv_obj_create(ui_ContainerSetting);
    lv_obj_set_height(ui_PanelUpdate, 50);
    lv_obj_set_width(ui_PanelUpdate, lv_pct(90));
    lv_obj_set_x(ui_PanelUpdate, 0);
    lv_obj_set_y(ui_PanelUpdate, lv_pct(60));
    lv_obj_set_align(ui_PanelUpdate, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelUpdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPanelUpdate = lv_label_create(ui_PanelUpdate);
    lv_obj_set_width(ui_LabelPanelUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPanelUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelUpdate, "UPDATE");

    ui_PanelValue = lv_obj_create(ui_ContainerSetting);
    lv_obj_set_height(ui_PanelValue, 50);
    lv_obj_set_width(ui_PanelValue, lv_pct(90));
    lv_obj_set_x(ui_PanelValue, 0);
    lv_obj_set_y(ui_PanelValue, lv_pct(80));
    lv_obj_set_align(ui_PanelValue, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPanelValue = lv_label_create(ui_PanelValue);
    lv_obj_set_width(ui_LabelPanelValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPanelValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelValue, "VALUE");

    ui_PanelConnect = lv_obj_create(ui_ContainerSetting);
    lv_obj_set_height(ui_PanelConnect, 26);
    lv_obj_set_width(ui_PanelConnect, lv_pct(90));
    lv_obj_set_x(ui_PanelConnect, 0);
    lv_obj_set_y(ui_PanelConnect, -130);
    lv_obj_set_align(ui_PanelConnect, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelConnect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiDisconnected = lv_img_create(ui_PanelConnect);
    lv_img_set_src(ui_WiFiDisconnected, &ui_img_1277404635);
    lv_obj_set_width(ui_WiFiDisconnected, 24);
    lv_obj_set_height(ui_WiFiDisconnected, 24);
    lv_obj_set_x(ui_WiFiDisconnected, 90);
    lv_obj_set_y(ui_WiFiDisconnected, 0);
    lv_obj_set_align(ui_WiFiDisconnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiDisconnected, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiDisconnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiConnected = lv_img_create(ui_PanelConnect);
    lv_img_set_src(ui_WiFiConnected, &ui_img_1300861977);
    lv_obj_set_width(ui_WiFiConnected, 24);
    lv_obj_set_height(ui_WiFiConnected, 24);
    lv_obj_set_x(ui_WiFiConnected, 90);
    lv_obj_set_y(ui_WiFiConnected, 0);
    lv_obj_set_align(ui_WiFiConnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiConnected, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiConnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoraConnected = lv_img_create(ui_PanelConnect);
    lv_img_set_src(ui_LoraConnected, &ui_img_1381526408);
    lv_obj_set_width(ui_LoraConnected, 24);
    lv_obj_set_height(ui_LoraConnected, 24);
    lv_obj_set_x(ui_LoraConnected, -90);
    lv_obj_set_y(ui_LoraConnected, 0);
    lv_obj_set_align(ui_LoraConnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoraConnected, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LoraConnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoraDisonnected = lv_img_create(ui_PanelConnect);
    lv_img_set_src(ui_LoraDisonnected, &ui_img_599427730);
    lv_obj_set_width(ui_LoraDisonnected, 24);
    lv_obj_set_height(ui_LoraDisonnected, 24);
    lv_obj_set_x(ui_LoraDisonnected, -90);
    lv_obj_set_y(ui_LoraDisonnected, 0);
    lv_obj_set_align(ui_LoraDisonnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoraDisonnected, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LoraDisonnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bell = lv_img_create(ui_PanelConnect);
    lv_img_set_src(ui_Bell, &ui_img_1704994528);
    lv_obj_set_width(ui_Bell, 24);
    lv_obj_set_height(ui_Bell, 24);
    lv_obj_set_x(ui_Bell, -60);
    lv_obj_set_y(ui_Bell, 0);
    lv_obj_set_align(ui_Bell, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bell, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Bell, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bellflash = lv_img_create(ui_PanelConnect);
    lv_img_set_src(ui_Bellflash, &ui_img_1666319769);
    lv_obj_set_width(ui_Bellflash, 24);
    lv_obj_set_height(ui_Bellflash, 24);
    lv_obj_set_x(ui_Bellflash, -60);
    lv_obj_set_y(ui_Bellflash, 0);
    lv_obj_set_align(ui_Bellflash, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bellflash, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Bellflash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTime = lv_label_create(ui_PanelConnect);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "00:00:00");

    lv_obj_add_event_cb(ui_PanelInternet, ui_event_PanelInternet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelTime, ui_event_PanelTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelUpdate, ui_event_PanelUpdate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelValue, ui_event_PanelValue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_ContainerSetting = NULL;
    ui_PanelInternet = NULL;
    ui_LabelPanelInternet = NULL;
    ui_PanelTime = NULL;
    ui_LabelPanelTime = NULL;
    ui_PanelUpdate = NULL;
    ui_LabelPanelUpdate = NULL;
    ui_PanelValue = NULL;
    ui_LabelPanelValue = NULL;
    ui_PanelConnect = NULL;
    ui_WiFiDisconnected = NULL;
    ui_WiFiConnected = NULL;
    ui_LoraConnected = NULL;
    ui_LoraDisonnected = NULL;
    ui_Bell = NULL;
    ui_Bellflash = NULL;
    ui_LabelTime = NULL;

}
