// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#ifndef UI_SCREEN0_H
#define UI_SCREEN0_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen0
extern void ui_Screen0_screen_init(void);
extern void ui_Screen0_screen_destroy(void);
extern void ui_event_Screen0(lv_event_t * e);
extern lv_obj_t * ui_Screen0;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

