// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#include "ui.h"

lv_obj_t * ui_Screen8 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_PanelValue1 = NULL;
lv_obj_t * ui_Value1Max = NULL;
lv_obj_t * ui_Value1Min = NULL;
lv_obj_t * ui_LabelValue1 = NULL;
lv_obj_t * ui_PanelValue2 = NULL;
lv_obj_t * ui_Value2Max = NULL;
lv_obj_t * ui_Value2Min = NULL;
lv_obj_t * ui_LabelValue2 = NULL;
lv_obj_t * ui_PanelValue3 = NULL;
lv_obj_t * ui_Value3Max = NULL;
lv_obj_t * ui_Value3Min = NULL;
lv_obj_t * ui_LabelValue3 = NULL;
lv_obj_t * ui_PanelValue4 = NULL;
lv_obj_t * ui_Value4Max = NULL;
lv_obj_t * ui_Value4Min = NULL;
lv_obj_t * ui_LabelValue4 = NULL;
lv_obj_t * ui_PanelValue5 = NULL;
lv_obj_t * ui_Value5Max = NULL;
lv_obj_t * ui_Value5Min = NULL;
lv_obj_t * ui_LabelValue5 = NULL;
// event funtions
void ui_event_Screen8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Screen8);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, lv_pct(100));
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0xAFD5C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue1 = lv_obj_create(ui_Screen8);
    lv_obj_set_height(ui_PanelValue1, 50);
    lv_obj_set_width(ui_PanelValue1, lv_pct(90));
    lv_obj_set_x(ui_PanelValue1, 0);
    lv_obj_set_y(ui_PanelValue1, -100);
    lv_obj_set_align(ui_PanelValue1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelValue1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Value1Max = lv_textarea_create(ui_PanelValue1);
    lv_obj_set_width(ui_Value1Max, lv_pct(30));
    lv_obj_set_height(ui_Value1Max, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Value1Max, 70);
    lv_obj_set_y(ui_Value1Max, lv_pct(0));
    lv_obj_set_align(ui_Value1Max, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Value1Max, "Max");
    lv_textarea_set_one_line(ui_Value1Max, true);

    ui_Value1Min = lv_textarea_create(ui_PanelValue1);
    lv_obj_set_width(ui_Value1Min, lv_pct(30));
    lv_obj_set_height(ui_Value1Min, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_Value1Min, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Value1Min, "Min");
    lv_textarea_set_one_line(ui_Value1Min, true);

    ui_LabelValue1 = lv_label_create(ui_PanelValue1);
    lv_obj_set_width(ui_LabelValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelValue1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelValue1, "Value 1:");

    ui_PanelValue2 = lv_obj_create(ui_Screen8);
    lv_obj_set_height(ui_PanelValue2, 50);
    lv_obj_set_width(ui_PanelValue2, lv_pct(90));
    lv_obj_set_x(ui_PanelValue2, 0);
    lv_obj_set_y(ui_PanelValue2, -50);
    lv_obj_set_align(ui_PanelValue2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelValue2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Value2Max = lv_textarea_create(ui_PanelValue2);
    lv_obj_set_width(ui_Value2Max, lv_pct(30));
    lv_obj_set_height(ui_Value2Max, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Value2Max, 70);
    lv_obj_set_y(ui_Value2Max, lv_pct(0));
    lv_obj_set_align(ui_Value2Max, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Value2Max, "Max");
    lv_textarea_set_one_line(ui_Value2Max, true);

    ui_Value2Min = lv_textarea_create(ui_PanelValue2);
    lv_obj_set_width(ui_Value2Min, lv_pct(30));
    lv_obj_set_height(ui_Value2Min, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_Value2Min, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Value2Min, "Min");
    lv_textarea_set_one_line(ui_Value2Min, true);

    ui_LabelValue2 = lv_label_create(ui_PanelValue2);
    lv_obj_set_width(ui_LabelValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelValue2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelValue2, "Value 2:");

    ui_PanelValue3 = lv_obj_create(ui_Screen8);
    lv_obj_set_height(ui_PanelValue3, 50);
    lv_obj_set_width(ui_PanelValue3, lv_pct(90));
    lv_obj_set_align(ui_PanelValue3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelValue3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Value3Max = lv_textarea_create(ui_PanelValue3);
    lv_obj_set_width(ui_Value3Max, lv_pct(30));
    lv_obj_set_height(ui_Value3Max, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Value3Max, 70);
    lv_obj_set_y(ui_Value3Max, lv_pct(0));
    lv_obj_set_align(ui_Value3Max, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Value3Max, "Max");
    lv_textarea_set_one_line(ui_Value3Max, true);

    ui_Value3Min = lv_textarea_create(ui_PanelValue3);
    lv_obj_set_width(ui_Value3Min, lv_pct(30));
    lv_obj_set_height(ui_Value3Min, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_Value3Min, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Value3Min, "Min");
    lv_textarea_set_one_line(ui_Value3Min, true);

    ui_LabelValue3 = lv_label_create(ui_PanelValue3);
    lv_obj_set_width(ui_LabelValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelValue3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelValue3, "Value 3:");

    ui_PanelValue4 = lv_obj_create(ui_Screen8);
    lv_obj_set_height(ui_PanelValue4, 50);
    lv_obj_set_width(ui_PanelValue4, lv_pct(90));
    lv_obj_set_x(ui_PanelValue4, 0);
    lv_obj_set_y(ui_PanelValue4, 50);
    lv_obj_set_align(ui_PanelValue4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelValue4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Value4Max = lv_textarea_create(ui_PanelValue4);
    lv_obj_set_width(ui_Value4Max, lv_pct(30));
    lv_obj_set_height(ui_Value4Max, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Value4Max, 70);
    lv_obj_set_y(ui_Value4Max, lv_pct(0));
    lv_obj_set_align(ui_Value4Max, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Value4Max, "Max");
    lv_textarea_set_one_line(ui_Value4Max, true);

    ui_Value4Min = lv_textarea_create(ui_PanelValue4);
    lv_obj_set_width(ui_Value4Min, lv_pct(30));
    lv_obj_set_height(ui_Value4Min, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_Value4Min, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Value4Min, "Min");
    lv_textarea_set_one_line(ui_Value4Min, true);

    ui_LabelValue4 = lv_label_create(ui_PanelValue4);
    lv_obj_set_width(ui_LabelValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelValue4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelValue4, "Value 4:");

    ui_PanelValue5 = lv_obj_create(ui_Screen8);
    lv_obj_set_height(ui_PanelValue5, 50);
    lv_obj_set_width(ui_PanelValue5, lv_pct(90));
    lv_obj_set_x(ui_PanelValue5, 0);
    lv_obj_set_y(ui_PanelValue5, 100);
    lv_obj_set_align(ui_PanelValue5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelValue5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Value5Max = lv_textarea_create(ui_PanelValue5);
    lv_obj_set_width(ui_Value5Max, lv_pct(30));
    lv_obj_set_height(ui_Value5Max, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Value5Max, 70);
    lv_obj_set_y(ui_Value5Max, lv_pct(0));
    lv_obj_set_align(ui_Value5Max, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Value5Max, "Max");
    lv_textarea_set_one_line(ui_Value5Max, true);

    ui_Value5Min = lv_textarea_create(ui_PanelValue5);
    lv_obj_set_width(ui_Value5Min, lv_pct(30));
    lv_obj_set_height(ui_Value5Min, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_Value5Min, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Value5Min, "Min");
    lv_textarea_set_one_line(ui_Value5Min, true);

    ui_LabelValue5 = lv_label_create(ui_PanelValue5);
    lv_obj_set_width(ui_LabelValue5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelValue5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelValue5, "Value 5:");

    lv_obj_add_event_cb(ui_Screen8, ui_event_Screen8, LV_EVENT_ALL, NULL);

}

void ui_Screen8_screen_destroy(void)
{
    if(ui_Screen8) lv_obj_del(ui_Screen8);

    // NULL screen variables
    ui_Screen8 = NULL;
    ui_Container4 = NULL;
    ui_PanelValue1 = NULL;
    ui_Value1Max = NULL;
    ui_Value1Min = NULL;
    ui_LabelValue1 = NULL;
    ui_PanelValue2 = NULL;
    ui_Value2Max = NULL;
    ui_Value2Min = NULL;
    ui_LabelValue2 = NULL;
    ui_PanelValue3 = NULL;
    ui_Value3Max = NULL;
    ui_Value3Min = NULL;
    ui_LabelValue3 = NULL;
    ui_PanelValue4 = NULL;
    ui_Value4Max = NULL;
    ui_Value4Min = NULL;
    ui_LabelValue4 = NULL;
    ui_PanelValue5 = NULL;
    ui_Value5Max = NULL;
    ui_Value5Min = NULL;
    ui_LabelValue5 = NULL;

}
