// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_PanelData;
extern lv_obj_t * ui_ImagePower;
extern lv_obj_t * ui_ImageCurrent;
extern lv_obj_t * ui_ImageVoltage;
extern lv_obj_t * ui_ImageSunny;
extern lv_obj_t * ui_ImageAir;
extern lv_obj_t * ui_LabelPower;
extern lv_obj_t * ui_LabeVoltage;
extern lv_obj_t * ui_LabeCurrent;
extern lv_obj_t * ui_LabeWeather;
extern lv_obj_t * ui_LabeAir;
extern lv_obj_t * ui_ImageCloudy;
extern lv_obj_t * ui_ImageRainy;
extern lv_obj_t * ui_ImageWindy;
extern lv_obj_t * ui_ImageSnowy;
extern lv_obj_t * ui_PanelArc;
extern void ui_event_ArcHumid(lv_event_t * e);
extern lv_obj_t * ui_ArcHumid;
extern lv_obj_t * ui_LabelhumidValue;
extern lv_obj_t * ui_LabelHumid;
extern void ui_event_ArcTemp(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp;
extern lv_obj_t * ui_LabelTempValue;
extern lv_obj_t * ui_LabelTemp;
extern void ui_event_ArcSoid(lv_event_t * e);
extern lv_obj_t * ui_ArcSoid;
extern void ui_event_LabelSoidValue(lv_event_t * e);
extern lv_obj_t * ui_LabelSoidValue;
extern lv_obj_t * ui_LabelSoid;
extern lv_obj_t * ui_PanelButton;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_LabelButton1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_LabelButton2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_LabelButton3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_LabelButton4;
extern lv_obj_t * ui_PanelDate;
extern lv_obj_t * ui_LabelDay;
extern lv_obj_t * ui_LabelDayinmonth;
extern lv_obj_t * ui_PanelConnect2;
extern lv_obj_t * ui_WiFiDisconnected2;
extern lv_obj_t * ui_WiFiConnected2;
extern lv_obj_t * ui_LoraConnected2;
extern lv_obj_t * ui_LoraDisonnected2;
extern lv_obj_t * ui_BellScreen;
extern lv_obj_t * ui_BellflashScreen;
extern lv_obj_t * ui_LabelTime2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

