// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_ContainerSetting;
extern void ui_event_PanelInternet(lv_event_t * e);
extern lv_obj_t * ui_PanelInternet;
extern lv_obj_t * ui_LabelPanelInternet;
extern void ui_event_PanelTime(lv_event_t * e);
extern lv_obj_t * ui_PanelTime;
extern lv_obj_t * ui_LabelPanelTime;
extern void ui_event_PanelUpdate(lv_event_t * e);
extern lv_obj_t * ui_PanelUpdate;
extern lv_obj_t * ui_LabelPanelUpdate;
extern void ui_event_PanelValue(lv_event_t * e);
extern lv_obj_t * ui_PanelValue;
extern lv_obj_t * ui_LabelPanelValue;
extern lv_obj_t * ui_PanelConnect;
extern lv_obj_t * ui_WiFiDisconnected;
extern lv_obj_t * ui_WiFiConnected;
extern lv_obj_t * ui_LoraConnected;
extern lv_obj_t * ui_LoraDisonnected;
extern lv_obj_t * ui_Bell;
extern lv_obj_t * ui_Bellflash;
extern lv_obj_t * ui_LabelTime;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

