// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#include "ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_PanelTimesetting = NULL;
lv_obj_t * ui_RollerMinute = NULL;
lv_obj_t * ui_RollerHour = NULL;
lv_obj_t * ui_PanelTimeButton = NULL;
lv_obj_t * ui_ButtonSet = NULL;
lv_obj_t * ui_LabelBTNSet = NULL;
lv_obj_t * ui_ButtonClear = NULL;
lv_obj_t * ui_LabelBTNClear = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Calendar1 = NULL;
// event funtions
void ui_event_Screen6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_ButtonSet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_roller_set_property(ui_RollerMinute, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 12);
        _ui_roller_set_property(ui_RollerHour, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 12);
    }
}

void ui_event_ButtonClear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_roller_set_property(ui_RollerMinute, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 0);
        _ui_roller_set_property(ui_RollerHour, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 0);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container8 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(100));
    lv_obj_set_height(ui_Container8, lv_pct(100));
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container8, lv_color_hex(0xAFD5C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimesetting = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_PanelTimesetting, lv_pct(70));
    lv_obj_set_height(ui_PanelTimesetting, lv_pct(20));
    lv_obj_set_x(ui_PanelTimesetting, 0);
    lv_obj_set_y(ui_PanelTimesetting, lv_pct(1));
    lv_obj_set_align(ui_PanelTimesetting, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelTimesetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollerMinute = lv_roller_create(ui_PanelTimesetting);
    lv_roller_set_options(ui_RollerMinute,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerMinute, lv_pct(40));
    lv_obj_set_height(ui_RollerMinute, lv_pct(156));
    lv_obj_set_x(ui_RollerMinute, lv_pct(30));
    lv_obj_set_y(ui_RollerMinute, lv_pct(0));
    lv_obj_set_align(ui_RollerMinute, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerMinute, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerHour = lv_roller_create(ui_PanelTimesetting);
    lv_roller_set_options(ui_RollerHour,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerHour, lv_pct(40));
    lv_obj_set_height(ui_RollerHour, lv_pct(156));
    lv_obj_set_align(ui_RollerHour, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_text_font(ui_RollerHour, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimeButton = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_PanelTimeButton, lv_pct(90));
    lv_obj_set_height(ui_PanelTimeButton, lv_pct(15));
    lv_obj_set_x(ui_PanelTimeButton, 0);
    lv_obj_set_y(ui_PanelTimeButton, 130);
    lv_obj_set_align(ui_PanelTimeButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTimeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonSet = lv_btn_create(ui_PanelTimeButton);
    lv_obj_set_height(ui_ButtonSet, 40);
    lv_obj_set_width(ui_ButtonSet, lv_pct(40));
    lv_obj_set_x(ui_ButtonSet, -50);
    lv_obj_set_y(ui_ButtonSet, 0);
    lv_obj_set_align(ui_ButtonSet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBTNSet = lv_label_create(ui_ButtonSet);
    lv_obj_set_width(ui_LabelBTNSet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBTNSet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBTNSet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBTNSet, "Set");

    ui_ButtonClear = lv_btn_create(ui_PanelTimeButton);
    lv_obj_set_height(ui_ButtonClear, 40);
    lv_obj_set_width(ui_ButtonClear, lv_pct(40));
    lv_obj_set_x(ui_ButtonClear, 50);
    lv_obj_set_y(ui_ButtonClear, 0);
    lv_obj_set_align(ui_ButtonClear, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonClear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBTNClear = lv_label_create(ui_ButtonClear);
    lv_obj_set_width(ui_LabelBTNClear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBTNClear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBTNClear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBTNClear, "Clear");

    ui_Panel9 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel9, lv_pct(100));
    lv_obj_set_height(ui_Panel9, lv_pct(60));
    lv_obj_set_x(ui_Panel9, lv_pct(0));
    lv_obj_set_y(ui_Panel9, lv_pct(2));
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar1 = lv_calendar_create(ui_Panel9);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, lv_pct(110));
    lv_obj_set_height(ui_Calendar1, lv_pct(110));
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ButtonSet, ui_event_ButtonSet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonClear, ui_event_ButtonClear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Container8 = NULL;
    ui_PanelTimesetting = NULL;
    ui_RollerMinute = NULL;
    ui_RollerHour = NULL;
    ui_PanelTimeButton = NULL;
    ui_ButtonSet = NULL;
    ui_LabelBTNSet = NULL;
    ui_ButtonClear = NULL;
    ui_LabelBTNClear = NULL;
    ui_Panel9 = NULL;
    ui_Calendar1 = NULL;

}
