// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_farming

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_PanelData = NULL;
lv_obj_t * ui_ImagePower = NULL;
lv_obj_t * ui_ImageCurrent = NULL;
lv_obj_t * ui_ImageVoltage = NULL;
lv_obj_t * ui_ImageSunny = NULL;
lv_obj_t * ui_ImageAir = NULL;
lv_obj_t * ui_LabelPower = NULL;
lv_obj_t * ui_LabeVoltage = NULL;
lv_obj_t * ui_LabeCurrent = NULL;
lv_obj_t * ui_LabeWeather = NULL;
lv_obj_t * ui_LabeAir = NULL;
lv_obj_t * ui_ImageCloudy = NULL;
lv_obj_t * ui_ImageRainy = NULL;
lv_obj_t * ui_ImageWindy = NULL;
lv_obj_t * ui_ImageSnowy = NULL;
lv_obj_t * ui_PanelArc = NULL;
lv_obj_t * ui_ArcHumid = NULL;
lv_obj_t * ui_LabelhumidValue = NULL;
lv_obj_t * ui_LabelHumid = NULL;
lv_obj_t * ui_ArcTemp = NULL;
lv_obj_t * ui_LabelTempValue = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_ArcSoid = NULL;
lv_obj_t * ui_LabelSoidValue = NULL;
lv_obj_t * ui_LabelSoid = NULL;
lv_obj_t * ui_PanelButton = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_LabelButton1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_LabelButton2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_LabelButton3 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_LabelButton4 = NULL;
lv_obj_t * ui_PanelDate = NULL;
lv_obj_t * ui_LabelDay = NULL;
lv_obj_t * ui_LabelDayinmonth = NULL;
lv_obj_t * ui_PanelConnect2 = NULL;
lv_obj_t * ui_WiFiDisconnected2 = NULL;
lv_obj_t * ui_WiFiConnected2 = NULL;
lv_obj_t * ui_LoraConnected2 = NULL;
lv_obj_t * ui_LoraDisonnected2 = NULL;
lv_obj_t * ui_BellScreen = NULL;
lv_obj_t * ui_BellflashScreen = NULL;
lv_obj_t * ui_LabelTime2 = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 100, 0, &ui_Screen3_screen_init);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_screen_change(&ui_Screen0, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen0_screen_init);
    }
}

void ui_event_ArcHumid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelhumidValue, target, "", "%");
    }
}

void ui_event_ArcTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelTempValue, target, "", "°C");
    }
}

void ui_event_ArcSoid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelSoidValue, target, "", "%");
    }
}

void ui_event_LabelSoidValue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelSoidValue, target, "", "");
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Pump_Click_callback(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Light_Click_callback(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_LabelButton4, _UI_LABEL_PROPERTY_TEXT, "Man");
        Mode_callback(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container);
    lv_obj_set_width(ui_Container, 240);
    lv_obj_set_height(ui_Container, 320);
    lv_obj_set_align(ui_Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Container);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 240);
    lv_obj_set_height(ui_Container1, 320);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 10);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelData = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_PanelData, 120);
    lv_obj_set_height(ui_PanelData, 160);
    lv_obj_set_x(ui_PanelData, -57);
    lv_obj_set_y(ui_PanelData, -70);
    lv_obj_set_align(ui_PanelData, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelData, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelData, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelData, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePower = lv_img_create(ui_PanelData);
    lv_img_set_src(ui_ImagePower, &ui_img_611426437);
    lv_obj_set_width(ui_ImagePower, 24);
    lv_obj_set_height(ui_ImagePower, 24);
    lv_obj_set_x(ui_ImagePower, -39);
    lv_obj_set_y(ui_ImagePower, -64);
    lv_obj_set_align(ui_ImagePower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePower, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCurrent = lv_img_create(ui_PanelData);
    lv_img_set_src(ui_ImageCurrent, &ui_img_290163073);
    lv_obj_set_width(ui_ImageCurrent, 24);
    lv_obj_set_height(ui_ImageCurrent, 24);
    lv_obj_set_x(ui_ImageCurrent, -39);
    lv_obj_set_y(ui_ImageCurrent, -32);
    lv_obj_set_align(ui_ImageCurrent, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCurrent, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCurrent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageVoltage = lv_img_create(ui_PanelData);
    lv_img_set_src(ui_ImageVoltage, &ui_img_611426437);
    lv_obj_set_width(ui_ImageVoltage, 24);
    lv_obj_set_height(ui_ImageVoltage, 24);
    lv_obj_set_x(ui_ImageVoltage, -39);
    lv_obj_set_y(ui_ImageVoltage, 0);
    lv_obj_set_align(ui_ImageVoltage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageVoltage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageVoltage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSunny = lv_img_create(ui_PanelData);
    lv_img_set_src(ui_ImageSunny, &ui_img_25085410);
    lv_obj_set_width(ui_ImageSunny, 24);
    lv_obj_set_height(ui_ImageSunny, 24);
    lv_obj_set_x(ui_ImageSunny, -39);
    lv_obj_set_y(ui_ImageSunny, 32);
    lv_obj_set_align(ui_ImageSunny, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSunny, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSunny, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAir = lv_img_create(ui_PanelData);
    lv_img_set_src(ui_ImageAir, &ui_img_1286666203);
    lv_obj_set_width(ui_ImageAir, 24);
    lv_obj_set_height(ui_ImageAir, 24);
    lv_obj_set_x(ui_ImageAir, -39);
    lv_obj_set_y(ui_ImageAir, 64);
    lv_obj_set_align(ui_ImageAir, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAir, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAir, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPower = lv_label_create(ui_PanelData);
    lv_obj_set_width(ui_LabelPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPower, 25);
    lv_obj_set_y(ui_LabelPower, -64);
    lv_obj_set_align(ui_LabelPower, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelPower, "1234 Kw");
    lv_obj_set_style_text_color(ui_LabelPower, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeVoltage = lv_label_create(ui_PanelData);
    lv_obj_set_width(ui_LabeVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeVoltage, 25);
    lv_obj_set_y(ui_LabeVoltage, -32);
    lv_obj_set_align(ui_LabeVoltage, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabeVoltage, "223 V");
    lv_obj_set_style_text_color(ui_LabeVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeCurrent = lv_label_create(ui_PanelData);
    lv_obj_set_width(ui_LabeCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeCurrent, 25);
    lv_obj_set_y(ui_LabeCurrent, 0);
    lv_obj_set_align(ui_LabeCurrent, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabeCurrent, "0.3 A");
    lv_obj_set_style_text_color(ui_LabeCurrent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeWeather = lv_label_create(ui_PanelData);
    lv_obj_set_width(ui_LabeWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeWeather, 25);
    lv_obj_set_y(ui_LabeWeather, 32);
    lv_obj_set_align(ui_LabeWeather, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabeWeather, "Sunny");
    lv_obj_set_style_text_color(ui_LabeWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeAir = lv_label_create(ui_PanelData);
    lv_obj_set_width(ui_LabeAir, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeAir, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeAir, 25);
    lv_obj_set_y(ui_LabeAir, 64);
    lv_obj_set_align(ui_LabeAir, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabeAir, "Normal");
    lv_obj_set_style_text_color(ui_LabeAir, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeAir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCloudy = lv_img_create(ui_PanelData);
    lv_img_set_src(ui_ImageCloudy, &ui_img_471554236);
    lv_obj_set_width(ui_ImageCloudy, 24);
    lv_obj_set_height(ui_ImageCloudy, 24);
    lv_obj_set_x(ui_ImageCloudy, -39);
    lv_obj_set_y(ui_ImageCloudy, 32);
    lv_obj_set_align(ui_ImageCloudy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCloudy, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCloudy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageRainy = lv_img_create(ui_PanelData);
    lv_img_set_src(ui_ImageRainy, &ui_img_316858971);
    lv_obj_set_width(ui_ImageRainy, 24);
    lv_obj_set_height(ui_ImageRainy, 24);
    lv_obj_set_x(ui_ImageRainy, -39);
    lv_obj_set_y(ui_ImageRainy, 32);
    lv_obj_set_align(ui_ImageRainy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageRainy, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRainy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWindy = lv_img_create(ui_PanelData);
    lv_img_set_src(ui_ImageWindy, &ui_img_1085318842);
    lv_obj_set_width(ui_ImageWindy, 24);
    lv_obj_set_height(ui_ImageWindy, 24);
    lv_obj_set_x(ui_ImageWindy, -39);
    lv_obj_set_y(ui_ImageWindy, 32);
    lv_obj_set_align(ui_ImageWindy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWindy, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWindy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSnowy = lv_img_create(ui_PanelData);
    lv_img_set_src(ui_ImageSnowy, &ui_img_513413048);
    lv_obj_set_width(ui_ImageSnowy, 24);
    lv_obj_set_height(ui_ImageSnowy, 24);
    lv_obj_set_x(ui_ImageSnowy, -39);
    lv_obj_set_y(ui_ImageSnowy, 32);
    lv_obj_set_align(ui_ImageSnowy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSnowy, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSnowy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelArc = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_PanelArc, 100);
    lv_obj_set_height(ui_PanelArc, 240);
    lv_obj_set_x(ui_PanelArc, 60);
    lv_obj_set_y(ui_PanelArc, -30);
    lv_obj_set_align(ui_PanelArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelArc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcHumid = lv_arc_create(ui_PanelArc);
    lv_obj_set_width(ui_ArcHumid, 80);
    lv_obj_set_height(ui_ArcHumid, 80);
    lv_obj_set_x(ui_ArcHumid, 0);
    lv_obj_set_y(ui_ArcHumid, -75);
    lv_obj_set_align(ui_ArcHumid, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcHumid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_ArcHumid, 80);
    lv_obj_set_style_arc_width(ui_ArcHumid, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcHumid, lv_color_hex(0x70B4FB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHumid, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHumid, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcHumid, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcHumid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcHumid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcHumid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcHumid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcHumid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelhumidValue = lv_label_create(ui_ArcHumid);
    lv_obj_set_width(ui_LabelhumidValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelhumidValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelhumidValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelhumidValue, "90%");
    lv_obj_set_style_text_color(ui_LabelhumidValue, lv_color_hex(0x70B4FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelhumidValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_LabelhumidValue, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumid = lv_label_create(ui_ArcHumid);
    lv_obj_set_width(ui_LabelHumid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumid, 0);
    lv_obj_set_y(ui_LabelHumid, 15);
    lv_obj_set_align(ui_LabelHumid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumid, "Humid");
    lv_obj_set_style_text_font(ui_LabelHumid, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemp = lv_arc_create(ui_PanelArc);
    lv_obj_set_width(ui_ArcTemp, 80);
    lv_obj_set_height(ui_ArcTemp, 80);
    lv_obj_set_align(ui_ArcTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_range(ui_ArcTemp, 0, 70);
    lv_arc_set_value(ui_ArcTemp, 29);
    lv_obj_set_style_arc_width(ui_ArcTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0xF89235), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTemp, lv_color_hex(0xF89235), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelTempValue = lv_label_create(ui_ArcTemp);
    lv_obj_set_width(ui_LabelTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempValue, "29°C");
    lv_obj_set_style_text_color(ui_LabelTempValue, lv_color_hex(0xF89235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_ArcTemp);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, 0);
    lv_obj_set_y(ui_LabelTemp, 15);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "Temp");
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcSoid = lv_arc_create(ui_PanelArc);
    lv_obj_set_width(ui_ArcSoid, 80);
    lv_obj_set_height(ui_ArcSoid, 80);
    lv_obj_set_x(ui_ArcSoid, 0);
    lv_obj_set_y(ui_ArcSoid, 75);
    lv_obj_set_align(ui_ArcSoid, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcSoid, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcSoid, 0, 50);
    lv_arc_set_value(ui_ArcSoid, 29);
    lv_obj_set_style_arc_width(ui_ArcSoid, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcSoid, lv_color_hex(0x744010), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSoid, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcSoid, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcSoid, lv_color_hex(0x744010), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcSoid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcSoid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcSoid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcSoid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcSoid, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSoidValue = lv_label_create(ui_ArcSoid);
    lv_obj_set_width(ui_LabelSoidValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSoidValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSoidValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSoidValue, "29%");
    lv_obj_set_style_text_color(ui_LabelSoidValue, lv_color_hex(0x744010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSoidValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSoid = lv_label_create(ui_ArcSoid);
    lv_obj_set_width(ui_LabelSoid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSoid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSoid, 0);
    lv_obj_set_y(ui_LabelSoid, 15);
    lv_obj_set_align(ui_LabelSoid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSoid, "Soid");
    lv_obj_set_style_text_font(ui_LabelSoid, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelButton = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_PanelButton, 120);
    lv_obj_set_height(ui_PanelButton, 130);
    lv_obj_set_x(ui_PanelButton, -57);
    lv_obj_set_y(ui_PanelButton, 80);
    lv_obj_set_align(ui_PanelButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelButton, lv_color_hex(0xAAF5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_PanelButton);
    lv_obj_set_width(ui_Button1, 50);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -28);
    lv_obj_set_y(ui_Button1, -28);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButton1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_LabelButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButton1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButton1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButton1, "Pump");

    ui_Button2 = lv_btn_create(ui_PanelButton);
    lv_obj_set_width(ui_Button2, 50);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 28);
    lv_obj_set_y(ui_Button2, -28);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButton2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_LabelButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButton2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButton2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButton2, "Fan");

    ui_Button3 = lv_btn_create(ui_PanelButton);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -28);
    lv_obj_set_y(ui_Button3, 28);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButton3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_LabelButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButton3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButton3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButton3, "Light");

    ui_Button4 = lv_btn_create(ui_PanelButton);
    lv_obj_set_width(ui_Button4, 50);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 28);
    lv_obj_set_y(ui_Button4, 28);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButton4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_LabelButton4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButton4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButton4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButton4, "Auto");

    ui_PanelDate = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_PanelDate, 100);
    lv_obj_set_height(ui_PanelDate, 50);
    lv_obj_set_x(ui_PanelDate, 60);
    lv_obj_set_y(ui_PanelDate, 120);
    lv_obj_set_align(ui_PanelDate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelDate, lv_color_hex(0x97F3C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDay = lv_label_create(ui_PanelDate);
    lv_obj_set_width(ui_LabelDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDay, -10);
    lv_obj_set_y(ui_LabelDay, -10);
    lv_obj_set_align(ui_LabelDay, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelDay, "Day: 28");
    lv_obj_set_style_text_color(ui_LabelDay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDayinmonth = lv_label_create(ui_PanelDate);
    lv_obj_set_width(ui_LabelDayinmonth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDayinmonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDayinmonth, -10);
    lv_obj_set_y(ui_LabelDayinmonth, 10);
    lv_obj_set_align(ui_LabelDayinmonth, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelDayinmonth, "Dec 24, 2025");
    lv_obj_set_style_text_color(ui_LabelDayinmonth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDayinmonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelConnect2 = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_PanelConnect2, 16);
    lv_obj_set_width(ui_PanelConnect2, lv_pct(90));
    lv_obj_set_align(ui_PanelConnect2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelConnect2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelConnect2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelConnect2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelConnect2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiDisconnected2 = lv_img_create(ui_PanelConnect2);
    lv_img_set_src(ui_WiFiDisconnected2, &ui_img_923752334);
    lv_obj_set_width(ui_WiFiDisconnected2, 16);
    lv_obj_set_height(ui_WiFiDisconnected2, 16);
    lv_obj_set_x(ui_WiFiDisconnected2, 90);
    lv_obj_set_y(ui_WiFiDisconnected2, 0);
    lv_obj_set_align(ui_WiFiDisconnected2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiDisconnected2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiDisconnected2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiConnected2 = lv_img_create(ui_PanelConnect2);
    lv_img_set_src(ui_WiFiConnected2, &ui_img_947216078);
    lv_obj_set_width(ui_WiFiConnected2, 16);
    lv_obj_set_height(ui_WiFiConnected2, 16);
    lv_obj_set_x(ui_WiFiConnected2, 90);
    lv_obj_set_y(ui_WiFiConnected2, 0);
    lv_obj_set_align(ui_WiFiConnected2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiConnected2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiConnected2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoraConnected2 = lv_img_create(ui_PanelConnect2);
    lv_img_set_src(ui_LoraConnected2, &ui_img_749987781);
    lv_obj_set_width(ui_LoraConnected2, 16);
    lv_obj_set_height(ui_LoraConnected2, 16);
    lv_obj_set_x(ui_LoraConnected2, -90);
    lv_obj_set_y(ui_LoraConnected2, 0);
    lv_obj_set_align(ui_LoraConnected2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoraConnected2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LoraConnected2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoraDisonnected2 = lv_img_create(ui_PanelConnect2);
    lv_img_set_src(ui_LoraDisonnected2, &ui_img_1564025377);
    lv_obj_set_width(ui_LoraDisonnected2, 16);
    lv_obj_set_height(ui_LoraDisonnected2, 16);
    lv_obj_set_x(ui_LoraDisonnected2, -90);
    lv_obj_set_y(ui_LoraDisonnected2, 0);
    lv_obj_set_align(ui_LoraDisonnected2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoraDisonnected2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LoraDisonnected2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BellScreen = lv_img_create(ui_PanelConnect2);
    lv_img_set_src(ui_BellScreen, &ui_img_1351346451);
    lv_obj_set_width(ui_BellScreen, 16);
    lv_obj_set_height(ui_BellScreen, 16);
    lv_obj_set_x(ui_BellScreen, -60);
    lv_obj_set_y(ui_BellScreen, 0);
    lv_obj_set_align(ui_BellScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BellScreen, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BellScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BellflashScreen = lv_img_create(ui_PanelConnect2);
    lv_img_set_src(ui_BellflashScreen, &ui_img_497137438);
    lv_obj_set_width(ui_BellflashScreen, 16);
    lv_obj_set_height(ui_BellflashScreen, 16);
    lv_obj_set_x(ui_BellflashScreen, -60);
    lv_obj_set_y(ui_BellflashScreen, 0);
    lv_obj_set_align(ui_BellflashScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BellflashScreen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BellflashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTime2 = lv_label_create(ui_PanelConnect2);
    lv_obj_set_width(ui_LabelTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime2, "00:00:00");

    lv_obj_add_event_cb(ui_ArcHumid, ui_event_ArcHumid, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcTemp, ui_event_ArcTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelSoidValue, ui_event_LabelSoidValue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSoid, ui_event_ArcSoid, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container = NULL;
    ui_Container1 = NULL;
    ui_PanelData = NULL;
    ui_ImagePower = NULL;
    ui_ImageCurrent = NULL;
    ui_ImageVoltage = NULL;
    ui_ImageSunny = NULL;
    ui_ImageAir = NULL;
    ui_LabelPower = NULL;
    ui_LabeVoltage = NULL;
    ui_LabeCurrent = NULL;
    ui_LabeWeather = NULL;
    ui_LabeAir = NULL;
    ui_ImageCloudy = NULL;
    ui_ImageRainy = NULL;
    ui_ImageWindy = NULL;
    ui_ImageSnowy = NULL;
    ui_PanelArc = NULL;
    ui_ArcHumid = NULL;
    ui_LabelhumidValue = NULL;
    ui_LabelHumid = NULL;
    ui_ArcTemp = NULL;
    ui_LabelTempValue = NULL;
    ui_LabelTemp = NULL;
    ui_ArcSoid = NULL;
    ui_LabelSoidValue = NULL;
    ui_LabelSoid = NULL;
    ui_PanelButton = NULL;
    ui_Button1 = NULL;
    ui_LabelButton1 = NULL;
    ui_Button2 = NULL;
    ui_LabelButton2 = NULL;
    ui_Button3 = NULL;
    ui_LabelButton3 = NULL;
    ui_Button4 = NULL;
    ui_LabelButton4 = NULL;
    ui_PanelDate = NULL;
    ui_LabelDay = NULL;
    ui_LabelDayinmonth = NULL;
    ui_PanelConnect2 = NULL;
    ui_WiFiDisconnected2 = NULL;
    ui_WiFiConnected2 = NULL;
    ui_LoraConnected2 = NULL;
    ui_LoraDisonnected2 = NULL;
    ui_BellScreen = NULL;
    ui_BellflashScreen = NULL;
    ui_LabelTime2 = NULL;

}
